version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: etudiants-db
    environment:
      POSTGRES_DB: etudiantsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks: [etudiants-net]

  redis:
    image: redis:alpine
    container_name: etudiants-redis
    networks: [etudiants-net]

  api:
    build: ./api-spring-boot
    container_name: etudiants-api
    ports: ["8080:8080"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/etudiantsdb
      SPRING_REDIS_HOST: redis
    depends_on: [db, redis]
    networks: [etudiants-net]

networks:
  etudiants-net:
    driver: bridge